### ISSUE TITLE
demo 报错

### ISSUE THREAD

**Issue by lifesign** [servicex-sh/dubbo-jetbrains-plugin#2]
![image](https://user-images.githubusercontent.com/2189610/157667923-10b251ad-bb96-46c2-8cae-274ca62667f3.png)

![image](https://user-images.githubusercontent.com/2189610/157667451-16e82327-91af-4d09-99e7-ac1d0a3629d6.png)
2021.3.2 版本

是还需要配置什么么

**Comment by lifesign** [comment]
UPDATE：本地启动服务之后，调用有报错，在入参中是使用全限定类名吗？

![image](https://user-images.githubusercontent.com/2189610/157790414-83f3bcad-deeb-4ed3-9c63-d366c7cc1f6d.png)

**Comment by linux-china** [comment]
所有的参数都要指定full class name，这个是Dubbo的要求 :)

**Comment by linux-china** [comment]
@lifesign  这个容错特性我觉得还是需要的，在0.3.0的版本我增加了该特性，允许Java的基本类型 ， 如int, Integer, String等，不需要添加java.lang这个前缀。如 `/GreetingsService/sayHi(String)` ，也能正确地工作。

 0.3.0版本已经提交JetBrains审核啦，应该2天就可以上线。
